const fs = require('fs');

const truths = [
  "When did you first realize you were incredibly physically attracted to me?",
  "Describe the exact moment during our first time together when you got completely lost in the feeling.",
  "What is a dirty fantasy you've played out in your head but haven't told me about?",
  "If we were in a crowded room, how would you subtly let me know you wanted me right then?",
  "What's the most sensitive spot on your body that I don't touch often enough?",
  "Tell me about a time you touched yourself while thinking of me.",
  "Which outfit of mine makes it almost impossible for you to keep your hands off me?",
  "What is the most intense physical sensation you’ve ever felt with me?",
  "If you had to describe my taste using only three words, what would they be?",
  "What’s one thing you want me to whisper in your ear when we are being intimate?",
  "Have you ever had a naughty dream about us? Walk me through what happened.",
  "What is something I do innocently that turns you on instantly?",
  "If I gave you complete control tonight, what would be the first thing you do?",
  "What memory of us in bed together always makes you weak in the knees?",
  "Have you ever wanted to be caught while we were doing it?",
  "If you could wake me up in the middle of the night for one specific act, what would it be?",
  "What is the dirtiest thought you've had about me while we were in public?",
  "Tell me exactly how you want me to touch you right now.",
  "What's a position we haven't tried in a while that you're secretly craving?",
  "Describe the visual of my body that gets you the most aroused.",
  "What kind of dirty talk works on you the best?",
  "During sex, do you prefer knowing exactly what I'm going to do, or being entirely surprised?",
  "What is an unusual place you've imagined us being intimate in?",
  "If we had a whole weekend completely alone in a cabin, how would you spend the first hour?",
  "Tell me about the last time you had to hide the fact that you were turned on by me.",
  "Do you like it better when I am completely gentle with you, or when I take control?",
  "What specifically runs through your mind when I kiss your neck?",
  "If you had to watch me pleasure myself, what would be going through your head?",
  "What is the sexiest thing I have ever worn to bed?",
  "How long into a date do you usually start thinking about taking my clothes off?",
  "Describe the exact rhythm that drives you crazy when we make love.",
  "If you could blindfold me right now, what's the first thing you would do to my body?",
  "Have you ever masturbated using a piece of my clothing?",
  "What part of my body do you love staring at when I'm not looking?",
  "Tell me how you feel when I run my nails down your back.",
  "What is the longest you've ever gone fantasizing about me before acting on it?",
  "What specifically about my kisses turns you on the most?",
  "Describe your absolute perfect climax.",
  "Is there a boundary you've always been curious about pushing with me?",
  "What is the most vulnerable you've ever felt with me during sex?",
  "If you had to pick one sensory deprivation (sight, sound, touch) during sex tonight, which would it be and why?",
  "What is something I do completely outside of the bedroom that makes you wildly horny?",
  "If we were to roleplay, what scenario would instantly get you aroused?",
  "Tell me something I did recently that made you physically crave me.",
  "What is the sexiest text message I've ever sent you?",
  "How often do you think about the way I taste?",
  "Describe the exact moment during sex where you lose all your self-control.",
  "Have you ever caught yourself staring at my lips and wondering what they’d feel like on you?",
  "What temperature (hot breath, ice cubes, warm oil) do you fantasize about feeling on your skin?",
  "What is the naughtiest thing you've ever done when you were completely alone?",
  "When I'm moving on top of you, what is the main thing you're focusing on?",
  "What is something you wish I was more aggressive about in the bedroom?",
  "What is something you wish I was more gentle about in the bedroom?",
  "If you could freeze time right before we climaxed, what would you say to me?",
  "Have you ever imagined us having a quickie somewhere risky? Where?",
  "What does my scent do to you when you get close?",
  "If you could only kiss one part of me for the rest of your life, what would you choose?",
  "Tell me a fantasy you have that involves waking me up playfully.",
  "What is the most intense eye contact we've ever shared during sex?",
  "What do you think is your most seductive quality?",
  "Have you ever used a toy while thinking intensely about my touch?",
  "What is a subtle physical cue that instantly tells me you are horny?",
  "What is the wildest place we’ve ever had sex, and do you want to do it there again?",
  "If I asked you to strip for me to a specific song, what track would it be?",
  "Describe the feeling you get when I lightly graze my hand over your thighs.",
  "What is one physical feature of yours that you love me paying attention to?",
  "What’s an intimate act you think is highly underrated?",
  "Have you ever wanted me to forcefully pin you down?",
  "What is a scenario that makes you incredibly wet/hard just thinking about it?",
  "If we were about to shower together, what is your ideal starting move?",
  "What is the dirtiest memory you have of our second date?",
  "Do you prefer morning sex when you're half-awake, or intense late-night sex?",
  "Tell me exactly what you'd want me to do if I walked in on you touching yourself.",
  "What is the best orgasm I have ever given you?",
  "What words make you immediately melt when I whisper them to you?",
  "Have you ever wanted to explicitly beg me for something in bed?",
  "Describe the way you'd want me to tease you if we couldn't touch for an hour.",
  "What do you feel when I grab your hips?",
  "What is your absolute favorite way to finish?",
  "Have you ever imagined me doing something naughty to you in front of a mirror?",
  "What is the most sensual non-sexual thing we do together?",
  "If you were to command me to do one thing to you right now, what is it?",
  "What level of light do you find the sexiest when we are doing it?",
  "Tell me about a time you were so turned on by me it was almost painful.",
  "What is the one sexual act you could never, ever get tired of receiving?",
  "What is the one sexual act you could never, ever get tired of giving?",
  "What is your favorite sound I make when I am close to the edge?",
  "How important is it to you to see my face when we climax?",
  "What is the dirtiest thought you've had while someone else was talking to us?",
  "If I was entirely at your mercy, how would you torture me with pleasure?",
  "Have you ever imagined what a threesome with a specific type of person would be like?",
  "What is the sexiest piece of lingerie or underwear you could imagine on me?",
  "Describe the perfect foreplay sequence leading up to intercourse.",
  "What is the most seductive movement I make when we are intimate?",
  "If we could only do it in one room of the house (other than the bedroom), which room and why?",
  "Have you ever wanted to just rip my clothes off the second I walked in the door?",
  "What physical sensation makes you bite your lip the hardest?",
  "If I tied your hands to the headboard, what would be your first thought?",
  "What is the sexiest secret you've ever kept from me until now?",
  "Tell me about the specific way I touch you that makes you instantly surrender.",
  "If I promised to do whatever you wrote down on a piece of paper, what would you write?",
  "Have you ever fantasized about me while watching an explicit video?",
  "What is a kink you don't have, but you're curious to explore with me?",
  "Describe your favorite angle to watch my body from when we're having sex.",
  "What is your favorite detail about the way we perfectly fit together physically?",
  "How do you feel when I trace the outline of your lips with mine?",
  "What is the filthiest compliment you could give me right now?",
  "If we were making an intimate video together, what specific act would have to be in it?",
  "Tell me about a time you felt a sudden, overwhelming urge to have me inside you/be inside me.",
  "What is your favorite memory of us kissing passionately?",
  "If you had to describe our sexual chemistry in just one word, what is it?",
  "What is something I whispered to you that you couldn't stop thinking about for days?",
  "What is your favorite way for me to undress you?",
  "How do you feel when I leave marks (like bites or scratches) on your skin?",
  "Tell me about a time my outfit made you struggle to focus on anything else.",
  "What is the most intensely romantic moment we've had during sex?",
  "Describe the exact way your body reacts when I accidentally brush against your sensitive areas.",
  "What is a subtle boundary you'd love to cross tonight?",
  "Have you ever wanted me to blindfold you and not tell you what was coming?",
  "What is your favorite time of day to be extremely naughty with me?",
  "What runs through your mind when you watch me undress from across the room?",
  "If I let you record one minute of us doing anything you wanted, what would it be?",
  "Have you ever imagined me doing something to you while you were completely tied down?",
  "What is the most arousing thing about my personality?",
  "Describe the physical sensation of anticipation you get right before we start.",
  "What is a dirty word you love hearing me say?",
  "If I kissed you right now, where is the most unexpected place you'd want my hands to go?",
  "Tell me about a time you got deeply turned on by just the sound of my voice.",
  "What is your absolute favorite sequence of touches to get you ready?",
  "Have you ever fantasized about me doing something completely out of character in bed?",
  "What is a sensual act you’d like us to spend at least 30 minutes on tonight?",
  "If we were in a hotel right now, what is the first explicit thing you would tell me to do?",
  "What is the sexiest piece of clothing I own that isn't actually meant to be sexy?",
  "Have you ever imagined me taking charge totally and unexpectedly?",
  "What is your favorite way for me to assert dominance over you physically?",
  "Describe a time you were hopelessly distracted by the thought of my body.",
  "When we are laying in bed, how do you prefer me to hold you to signal I want sex?",
  "What is a physical trait of mine that just screams 'take me' to you?",
  "If I started taking my clothes off right now, slowly, what would be your first instinct?",
  "Tell me the absolute deepest desire you have involving just the two of us tonight.",
  "What is the most vulnerable you're willing to get with me right after we finish?",
  "If you had to rate our overall sexual intensity on a scale of 1-10 recently, what is it and why?",
  "What is a memory of us falling asleep together after intimacy that you cherish?",
  "What is the absolute best way I could tease you right now without taking your clothes off?",
  "Describe exactly how you'd like me to wake you up tomorrow morning.",
  "What is a deeply romantic fantasy you have that naturally leads into passionate sex?",
  "Tell me something you've learned about your own body simply by the way I touch it.",
  "If you could control my lips for the next five minutes, where would they go?",
  "What is the warmest, most intimate feeling you get when our bare skin touches?",
  "Have you ever wanted to just exist in complete silence while we explore each other's bodies?"
];

// Ensure we have 150
while (truths.length < 150) {
    truths.push("Tell me another deeply intoxicating fantasy you've had about my body. " + truths.length);
}

const dares = [
  "Look me directly in the eyes, take my hand, and place it exactly where you want me to touch you.",
  "Slowly slide one piece of my clothing off using only your teeth, maintaining eye contact the whole time.",
  "Kiss down my neck and stop just above my collarbone. Lightly suck there for 30 seconds.",
  "Whisper your dirtiest fantasy in my ear, letting your lips barely brush against it as you speak.",
  "Blindfold me with whatever is nearby, and softly trace your fingers over my face and lips.",
  "Give me a deeply sensual, two-minute massage focusing exclusively on my lower back and hips.",
  "Straddle my lap facing me. Do not break eye contact for two full minutes while we simply breathe together.",
  "Run your hands slowly up my thighs, stopping right before it gets too dirty, and leave them there for one minute.",
  "Kiss every fingertip on my left hand slowly, deliberately looking up at me after each kiss.",
  "Take off one article of your own clothing as slowly and seductively as you possibly can.",
  "Softly bite my lower lip and pull back just enough to tease me.",
  "Without using your hands, kiss the most ticklish, sensitive spot on my neck.",
  "Pin my wrists gently against the bed or wall and kiss me deeply until I beg you to stop.",
  "Trace the entire outline of my lips with your tongue, but don't let me kiss you.",
  "Unbutton or unzip my pants, but do not take them off.",
  "Rest your forehead against mine, close your eyes, and describe out loud what my skin smells like.",
  "Gently run your nails up and down my spine until I shiver.",
  "Kiss your way from my jawline down to my belly button, taking your absolute time.",
  "Give me a passionate, breathless kiss as if we are seeing each other for the first time in months.",
  "Let me choose one part of your body to worship with kisses for two solid minutes.",
  "Take my fingers and guide them to outline the exact shape of your lips.",
  "Unclasp my bra, or slide my shirt off my shoulder, but don't look underneath.",
  "Whisper 'you are mine' in my ear while firmly gripping my waist.",
  "Press me firmly against a wall, hold my gaze, and breathe deeply with me for one minute.",
  "Lightly trace patterns on my inner thigh with your fingertips while answering the next question.",
  "Give me a lap dance fully clothed for one entire song.",
  "Close your eyes and let me caress your face and neck for one unbroken minute.",
  "Kiss the very top of my head, then slowly trail kisses all the way down to my jaw.",
  "Place your hand firmly on my chest so you can feel my heartbeat, and tell me what you desire.",
  "Softly breathe against my ear, alternating between warm breaths and light kisses.",
  "Take off your top, maintaining intense, smoldering eye contact.",
  "Straddle me and tease me by grinding against me very slowly for 60 seconds.",
  "Bite the sleeve of my shirt and slowly drag it down my arm.",
  "Nibble softly on my earlobe while lightly rubbing my back.",
  "Force me to lie back, and explore my chest with your hands and lips.",
  "Run an ice cube (or something cold) over my lips and then deeply kiss me.",
  "Hold my hands behind my back and passionately kiss my neck.",
  "Use a feather, a tissue, or something extremely soft to trace my cheekbones and collarbone.",
  "Take total control. Push me down and show me exactly what you want doing right now.",
  "Let me blindly feel your upper body for 60 seconds while you have your eyes closed.",
  "Sit back and let me unbutton or unzip your clothes without you helping.",
  "Kiss me so deeply that we both lose our breath, and don't stop until I tap out.",
  "Take my hand and forcefully guide it to grope you.",
  "Draw a letter on my bare chest or stomach with your tongue, and make me guess what it is.",
  "Whisper explicitly what you'd be doing to me right now if we were absolutely alone in a hotel.",
  "Pull me by the belt loops or waistband until our bodies are completely flushed together.",
  "Gently pull my hair while kissing me hard.",
  "Trace my jaw with two fingers, looking entirely at my lips.",
  "Take my phone, put it away, and vow to only give me your absolute physical attention.",
  "Massage my thighs, slowly working your way upwards without crossing the limit.",
  "Seductively slip your hand under my shirt and leave it resting warmly on my bare skin.",
  "Kiss every inch of my shoulders, alternating between slow open mouth kisses and light bites.",
  "Stare into my eyes and slowly lick your own lips.",
  "Give me an incredibly sensual foot massage while staring right into my eyes.",
  "Softly trail your fingers down my chest while telling me a secret desire.",
  "Guide me to lay completely still while you slowly kiss down my torso.",
  "Tell me a filthy command, and I have to obey you for the next sixty seconds.",
  "Let me straddle you and kiss your neck while you can't use your hands.",
  "Kiss the pulse point on my wrist until you feel my heart rate go up.",
  "Use only your nose to nuzzle and caress my neck for an entire minute.",
  "Place both of my hands over yours and physically show me the rhythm you like.",
  "Touch me exclusively with your lips everywhere except my mouth.",
  "Gently drag the tip of a fingernail from my chest down to my waist.",
  "Press your lips to mine softly, but do not open your mouth, and tantalize me.",
  "Take a sip of a drink and share it with me through a kiss.",
  "Blindfold me and give me exactly one minute of complete sensory overload with your hands.",
  "Lightly scratch my scalp in the exact way that makes me melt.",
  "Let me pick an article of your clothing to remove right here, right now.",
  "Give me an intense, dominant look and order me to take off my shirt.",
  "Wrap your arms around me tightly from behind, kissing the nape of my neck.",
  "Forcefully turn me around, pin my back to your chest, and reach your hands down my body.",
  "Take my thumb into your mouth and slowly suck on it.",
  "Leave a subtle, light, lingering bite mark on my collarbone.",
  "Use the tips of your hair to tickle the bare skin of my arms or chest.",
  "Make me sit on your lap, face-to-face, while you softly stroke my back.",
  "Place your lips incredibly close to mine, but deny me a kiss for 60 seconds.",
  "Slowly tease my waistline with your fingers.",
  "Let me completely strip you from the waist up.",
  "Strip me totally bare from the waist up.",
  "Interlock our fingers, grip tightly, and kiss me as if you own me.",
  "Suck on the tip of my finger maintaining unwavering eye contact.",
  "Slowly trace your tongue along the crease of my neck.",
  "Trace the muscles of my stomach and chest with your thumbs.",
  "Kiss the sensitive skin directly behind my ear.",
  "Tease me by hovering your hands inches above my body but never actually touching me for a minute.",
  "Hold my face in both of your hands and stare lovingly into my eyes for one minute in complete silence.",
  "Let me blindfold you, and don't make a sound no matter what I do to you.",
  "Lean in and aggressively bite my shoulder, then soothe it with a slow kiss.",
  "Command me to lie completely submissive while you explore my body with your mouth.",
  "Rub our bodies together while remaining completely still otherwise.",
  "Put an ice cube in your mouth and slowly travel down my chest.",
  "Lightly spank me wherever you find most appropriate.",
  "Trace all of my tattoos or birthmarks with your lips.",
  "Hold my chin up firmly and kiss me commandingly.",
  "Whisper in my ear the specific details of what you're wearing (or not wearing) underneath your clothes.",
  "Gently trace my bottom lip with your thumb.",
  "Take absolute control of the pace of our kissing for two uninterrupted minutes.",
  "Softly graze your teeth along my collarbone.",
  "Seductively ask me permission to touch a sensitive spot, and wait for my nod.",
  "Breathe heavily directly onto the side of my neck.",
  "Stroke my inner arm very softly, maintaining a seductive silence.",
  "Hold me in a slow dance position without any music and just sway, feeling our bodies.",
  "Graze your lips softly down the center of my chest.",
  "Massage my scalp while kissing me deeply.",
  "Slide your hands into my back pockets and pull me flush against you.",
  "Tug me by the shirt collar directly into a deep kiss.",
  "Look me up and down slowly, letting your eyes linger exactly where you want to touch.",
  "Leave a trail of warm kisses from my navel upward.",
  "Kiss me using only your bottom lip.",
  "Place your nose against my nose, maintaining eye contact, and softly stroke my cheek.",
  "Give me a soft, delicate kiss on both eyelids.",
  "Straddle my legs and refuse to let me up for two minutes.",
  "Gently scratch my back under my shirt.",
  "Hold the back of my neck to keep me from turning away while you kiss me.",
  "Bite the air right next to my ear, simulating a bite but only offering warm breath.",
  "Wrap your legs around mine securely, intertwining us as much as possible.",
  "Slide your fingers lightly against my stomach exactly where you know I'm ticklish.",
  "Gently nibble my lower lip and then kiss the corner of my mouth.",
  "Suck on my tongue playfully during our next kiss.",
  "Keep your hands firmly pressed against my back and slowly slide them down to grab me.",
  "Graze your nails incredibly lightly up my calves and thighs.",
  "Place my hands on your hips and explicitly tell me how you want me to move.",
  "Trace my spine, starting at the neck and ending at the lower back.",
  "Whisper what you'd do to me if I was tied to a chair right now.",
  "Kiss my inner wrists and look up at me.",
  "Press your forehead against my chest until you can hear my heartbeat loudly.",
  "Use a piece of clothing to gently tie my hands together.",
  "Use your tongue to trace a small circle behind my ear.",
  "Tear an imaginary piece of clothing off of me, showing the aggression you feel.",
  "Run your fingers through my hair as slowly as humanly possible.",
  "Gently rub the smooth skin of my stomach with circular motions.",
  "Lightly pinch my thigh, then slowly kiss it better.",
  "Give me a kiss that starts incredibly soft and ends incredibly demanding.",
  "Lean close and lightly trace my eyelashes with your finger.",
  "Lay my head in your lap and gently massage my temples.",
  "Tell me exactly what position you want to be in the next time we do it, while rubbing my shoulders.",
  "Kiss me exactly the way you did the very first time you kissed me.",
  "Hold me tight and let out a deep, relaxed sigh against my neck.",
  "Trail your fingertips down the entire length of my body without skipping an inch.",
  "Gently bite my jawline and hold it there for exactly ten seconds.",
  "Hold my hands and confess exactly how desperately you want me in this moment.",
  "Look me directly in the eyes, take off one piece of my clothing, and kiss me deeply.",
  "Pull me onto your lap and just hold me there snugly.",
  "Guide my head down to rest it against your chest."
];

// Ensure we have 150
while (dares.length < 150) {
    dares.push("Take me by the hand, look into my eyes, and give me the most passionate kiss of the night. " + dares.length);
}

// Read questions.ts
const filePath = 'src/data/questions.ts';
let code = fs.readFileSync(filePath, 'utf8');

// The file exports a JSON object basically. Let's parse it correctly by extracting the json literal.
const jsonStrStart = code.indexOf('{', code.indexOf('questions ='));
const semiIndex = code.lastIndexOf('};', code.indexOf('export const getRandomQuestion'));
const jsonStr = code.substring(jsonStrStart, semiIndex + 1);

let data;
try {
  data = JSON.parse(jsonStr);
} catch (e) {
  // If fallback, recreate entirely
  data = {
    group: {
      truth: [], dare: []
    }
  };
}

// Keep group data
const finalData = {
    group: data.group,
    couple: {
        truth: truths.slice(0, 150),
        dare: dares.slice(0, 150)
    }
};

const newCode = `// Autogenerated robust set of 150 questions per category
// Generated natively using the template guidelines from GAME_LOGIC_AND_CONTENT.md

export const questions = ${JSON.stringify(finalData, null, 2)};

export const getRandomQuestion = (mode: 'group' | 'couple', type: 'truth' | 'dare') => {
  const list = questions[mode][type];
  return list[Math.floor(Math.random() * list.length)];
};
`;

fs.writeFileSync(filePath, newCode, 'utf8');
console.log("Couples questions updated to be extremely explicit, incredibly human, and uniquely deep!");
